{% set name = "pyeviews" %}
{% set version = "1.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8a1ee00c1ba7da7b267b5a0607d877d7ba3ecf02a4616059ac0b836e301c750a

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [not win]

requirements:
  build:
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - numpy
    - pandas
    - comtypes
    - setuptools

test:
  imports:
    - pyeviews

about:
  home: http://github.com/bexer/pyeviews
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE.txt
  summary: Data import/export and EViews function calls from Python

  description: |
    The purpose of the pyeviews package is to make it easier for EViews and Python 
    to talk to each other, so Python programmers can use the econometric engine of 
    EViews directly from Python.
  dev_url: https://github.com/bexer/pyeviews

extra:
  recipe-maintainers:
    - bexer
