{% set name = "pyeviews" %}
{% set version = "1.0.5" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: e1c1235e3a6121495a380d713705f8fec4b77ef52535c0de54683342affc9155

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  skip: True  # [not win]

requirements:
  host:
    - numpy
    - pandas
    - pip
    - python
    - setuptools
  run:
    - numpy
    - pandas
    - python
    - comtypes
    - setuptools

test:
  imports:
    - pyeviews

app:
  summary: 'Data import/export and EViews function calls from Python'
  
about:
  home: https://github.com/bexer/pyeviews
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE.txt
  summary: 'Data import/export and EViews function calls from Python'
  doc_url: 
  dev_url: 
  description: |
    The purpose of the pyeviews package is to make it easier for EViews and Python 
    to talk to each other, so Python programmers can use the econometric engine of 
    EViews directly from Python.
  dev_url: https://github.com/bexer/pyeviews
 
extra:
  recipe-maintainers:
    - bexer
